outputPath: output
clientName: ${client:client}
providerName: ${server:server}

zuul:
  routes:
    proxy:
      path: /**
      url: ${remote}

ribbon:
  eureka:
    enabled: false

server:
  port: ${port:9999}
